fleatransaction:
    jwt:
        expire: 86400
        header: Authorization
        secret: f4e2e52034348f86b67cde581c0f9eb5
mybatis-plus:
    config-location: classpath:/mybatis-config.xml
    mapper-locations: classpath:/cn/fleatransaction/mapper/*.xml
server:
    port: 8888
shiro-redis:
    enabled: true
    redis-manager:
        host: 127.0.0.1:6379
spring:
    datasource:
        password: zjx20000701
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://127.0.0.1:3306/flea?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
        username: root
