fleatransaction:
    jwt:
        expire: 86400
        header: Authorization
        secret: f4e2e52034348f86b67cde581c0f9eb5
mybatis-plus:
    config-location: classpath:/mybatis-config.xml
    mapper-locations: classpath:/cn/fleatransaction/mapper/*.xml
server:
    port: 8082
shiro-redis:
    enabled: true
    redis-manager:
        host: 47.110.243.78:6379
        password: 199921y
spring:
    datasource:
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://47.110.243.78:3306/flea?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
        username: qwe
